### ISSUE TITLE
Client displayed on Add New Project page is different from Clients List page

### ISSUE THREAD

**Issue by PavanPotukuchik** [PavanPotukuchik/CITS5206_Group07#25]
Steps to Reproduce:
1.Login to Portal as Admin user
2.Navigate to Clients by clicking on “Clients” from left side navigation panel to view list of clients displayed.
3.From left side navigation panel, Click on Projects -> Click on Create Projects  -> Click on Select Client dropdown to view list of clients
Expected Result: Client displayed on Add New Project page should be same as Clients List page
[ClientListIssue.docx](https://github.com/user-attachments/files/17241373/ClientListIssue.docx)

**Comment by jankirangani** [comment]
It was the older version of it, and i only put it to test the functions, it is resolved now and merged into main branch.
